# Generated by Django 3.1.6 on 2021-05-16 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_spotlight_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumName', models.CharField(max_length=100)),
                ('noSongs', models.IntegerField()),
                ('albumArtist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music_spotlight_app.artists')),
            ],
        ),
    ]
