# Generated by Django 3.1.6 on 2021-05-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_spotlight_app', '0002_album_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='artistName',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
